### ISSUE TITLE
Twitch channel points

### ISSUE THREAD

**Issue by ahmedtds** [aidan-walden/Twitch-Rewards-Farmer#1]
Can you update this to work with and farm Twitch Channel Points please? Also auto-collecting bonus channel points. You know they require to click manually.

**Comment by aidan-walden** [comment]
Twitch has added an "I'm not a robot" captcha to the sign in. I have an idea for a solution but its a bit janky at the moment. I'm trying to think of a better way around this, and once I have that done I'll look into adding this.

**Comment by ahmedtds** [comment]
Thanks a lot for responding and working on it <3

Code on these extensions may be useful when you are looking into it:
https://github.com/xinitrc-dev/twitch-points-autoclicker
https://github.com/trmcnvn/twitch-channel-points
https://github.com/huigovnomuravei/twitch-points-claimer

**Comment by aidan-walden** [comment]
Hey, this feature has been added now! Thanks for the suggestion!

**Comment by ahmedtds** [comment]
Thanks a lot!
